In [52]:
#@title #####**Useful Functions**

# titanic.isnull().values.any()   # In entire dataset contains NAN value or not
# titanic.isnull().sum()  #column wise NAN value showing
# len(titanic['embark_town'].unique())
# titanic['embark_town'].unique()     no. of unique value in that column

# ds.shape    no. of rows
# ds.value.counts()  no. of classes
# ds.sort_values('column')
# pd.concat([df1,df2])
# train.values            .values will give the values in a numpy array (shape: (n,1))
# train.values.ravel()   .ravel will convert that array shape to (n, ) (i.e. flatten it)
# train_y.values.reshape(-1,)   another way of ravel()
# print(len(X_train))


**IRIS Dataset:** The iris data are a data frame of 150 measurements of iris petal and sepal lengths and widths, with 50 measurements for each species of “setosa,” “versicolor,” and “virginica.”

In [53]:
#@title #####**Loading the dataset**
import pandas as pd
import seaborn as sns   #seaborn provides function that help to quick access to small dataset
sns.get_dataset_names() #show all dataset  available
iris=sns.load_dataset('iris') #loaded iris dataset
# iris.isnull().values.any()   # In entire dataset contains NAN value or not
iris.isnull().sum()  #column wise NAN value showing
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [54]:
#@title #####**Counting the classes**
iris['species'] = iris.species.map( {'setosa':0.0 , 'versicolor':1.0, 'virginica':2.0} )
class_count=iris['species'].value_counts()
print(class_count)

0.0    50
1.0    50
2.0    50
Name: species, dtype: int64


In [55]:
#@title #####**Sort and Print the dataset**
iris1=iris.sort_values('species',ascending=True)
iris1

sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      0.0
27            5.2          3.5           1.5          0.2      0.0
28            5.2          3.4           1.4          0.2      0.0
29            4.7          3.2           1.6          0.2      0.0
30            4.8          3.1           1.6          0.2      0.0
..            ...          ...           ...          ...      ...
119           6.0          2.2           5.0          1.5      2.0
120           6.9          3.2           5.7          2.3      2.0
121           5.6          2.8           4.9          2.0      2.0
111           6.4          2.7           5.3          1.9      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [56]:
#@title #####**Break whole dataset into training data and testing data**

ds_0=iris1[:50]   #ds_0 === dataset with label=0
ds_1=iris1[50:100]
ds_2=iris1[100:150]
#ds_2.shape #no. of rows in dataset

ds_0_train=ds_0[:25]
ds_0_test=ds_0[25:]

ds_1_train=ds_1[:25]
ds_1_test=ds_1[25:]

ds_2_train=ds_2[:25]
ds_2_test=ds_2[25:]


frames1 = [ds_0_train,ds_1_train,ds_2_train]
train_ds = pd.concat(frames1)
# train_ds


frames2 = [ds_0_test,ds_1_test,ds_2_test]
test_ds = pd.concat(frames2)
# test_ds


train_ds_x=train_ds.iloc[:,:-1]
train_ds_y=train_ds.iloc[:,-1:]
# train_ds_y


test_ds_x=test_ds.iloc[:,:-1]
test_ds_y=test_ds.iloc[:,-1:]
# test_ds_x


train_x=train_ds_x;
train_y=train_ds_y.values.ravel();
test_x=test_ds_x;
test_y=test_ds_y.values.ravel();
# train_ds_y
print(len(train_x),len(test_x))

75 75


####**Using** **SVM**

In [57]:
#using support vector machine

from sklearn.svm import SVC # "Support vector classifier"
model = SVC(kernel='linear')
model.fit(train_x, train_y)
predictions = model.predict(test_x)
print(predictions)
print(test_y)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 2. 2. 2. 2. 2. 2. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2.]


In [58]:
percentage = model.score(test_x, test_y)
print("percentage : ",percentage)

percentage :  0.9866666666666667


In [59]:
# confusion matrix shows the errors in the model performance in the form of a matrix, known as an error matrix [test_y vs predictions].

from sklearn.metrics import confusion_matrix
res = confusion_matrix(test_y, predictions)
print("Confusion Matrix") # first row for class=0 and total 10 prediction is successful, 2nd row for class=1 in which 8 predictions are correct and 2 predictions are wrong , 3rd for class=2 similar to row1
print(res)
print(f"Test Set: {len(test_ds_x)}")
print(f"Accuracy = {percentage*100} %")

Confusion Matrix
[[25  0  0]
 [ 0 25  0]
 [ 0  1 24]]
Test Set: 75
Accuracy = 98.66666666666667 %


####**Using** **Linear** **Regression**


In [60]:
#using linear regression
from sklearn.linear_model import LinearRegression
model_1 = LinearRegression()

model_1.fit(train_x, train_y)
model_1.score(train_x, train_y)


0.9300492532626649